<a href="https://colab.research.google.com/github/timberking2/Machine_Learning/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("ca_offenses_by_city.csv")
#df.columns = df.columns.str.replace(' ', '_')
#df.columns = df.columns.str.replace('/', '_')
#df.columns = df.columns.str.replace('(', '')
#df.columns = df.columns.str.replace(')', '')
#df.columns = df.columns.str.replace('-', '_')
#df.columns = df.columns.str.replace(',', '')
#df.dropna ()

df
# Все замены были для /content/ca_offenses_by_county.csv, поменял цсвшник чтоб не мешали NaN'ы

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
0,Adelanto,"33,005",212,2,14,NaN,48,148,808,434,254,120,24
1,Agoura Hills,"20,970",15,0,1,NaN,6,8,310,82,217,11,0
2,Alameda,"78,613",148,2,7,NaN,61,78,"1,819",228,"1,245",346,18
3,Albany,"19,723",34,1,6,NaN,16,11,605,95,447,63,0
4,Alhambra3,"86,175",168,1,13,NaN,74,80,"1,929",305,"1,413",211,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Yountville3,"3,030",7,0,0,NaN,0,7,46,7,36,3,0
456,Yreka,"7,507",47,1,4,NaN,4,38,309,85,188,36,1
457,Yuba City,"65,974",216,0,28,NaN,66,122,"1,792",429,"1,160",203,14
458,Yucaipa,"53,498",94,2,8,NaN,22,62,"1,309",263,838,208,12
459,Yucca Valley,"21,672",151,0,8,NaN,30,113,664,217,381,66,8

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [ ]:
list(df.columns)

['City',
 'Population',
 'Violent crime',
 'Murder and nonnegligent manslaughter',
 'Rape (revised definition)',
 'Rape (legacy definition)',
 'Robbery',
 'Aggravated assault',
 'Property crime',
 'Burglary',
 'Larceny-theft',
 'Motor vehicle theft',
 'Arson']

In [ ]:
df.head(5)

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
0,Adelanto,"33,005",212,2,14,NaN,48,148,808,434,254,120,24
1,Agoura Hills,"20,970",15,0,1,NaN,6,8,310,82,217,11,0
2,Alameda,"78,613",148,2,7,NaN,61,78,"1,819",228,"1,245",346,18
3,Albany,"19,723",34,1,6,NaN,16,11,605,95,447,63,0
4,Alhambra3,"86,175",168,1,13,NaN,74,80,"1,929",305,"1,413",211,6

In [ ]:
df.tail(5)

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
455,Yountville3,"3,030",7,0,0,NaN,0,7,46,7,36,3,0
456,Yreka,"7,507",47,1,4,NaN,4,38,309,85,188,36,1
457,Yuba City,"65,974",216,0,28,NaN,66,122,"1,792",429,"1,160",203,14
458,Yucaipa,"53,498",94,2,8,NaN,22,62,"1,309",263,838,208,12
459,Yucca Valley,"21,672",151,0,8,NaN,30,113,664,217,381,66,8

In [ ]:
df.describe(include="all")

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
count,460,460,460,460.000000,460,0.0,460,460,460,460,460,460,460
unique,460,460,257,NaN,74,NaN,158,207,425,310,394,271,56
top,Adelanto,"33,005",1,NaN,0,NaN,0,1,150,80,64,3,0
freq,1,1,12,NaN,47,NaN,33,14,3,6,4,9,105
mean,NaN,NaN,NaN,3.165217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,14.971101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,282.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



1.  Ответ
2.  Ответ

In [ ]:
# Первый ответ
df.mean()

<ipython-input-114-9a6813b6fbe8>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

Murder and nonnegligent manslaughter    3.165217
Rape (legacy definition)                     NaN
dtype: float64

In [ ]:
# Второй ответ
df.min()

City                                     Adelanto
Population                              1,031,458
Violent crime                                   0
Murder and nonnegligent manslaughter            0
Rape (revised definition)                       0
Rape (legacy definition)                      NaN
Robbery                                         0
Aggravated assault                              0
Property crime                              1,028
Burglary                                        0
Larceny-theft                               1,004
Motor vehicle theft                             0
Arson                                           0
dtype: object

In [ ]:
#Второй ответ
df.max()

City                                    Yucca Valley
Population                                    99,706
Violent crime                                     99
Murder and nonnegligent manslaughter             282
Rape (revised definition)                         98
Rape (legacy definition)                         NaN
Robbery                                           99
Aggravated assault                                99
Property crime                                   998
Burglary                                          99
Larceny-theft                                    996
Motor vehicle theft                               99
Arson                                             93
dtype: object

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [ ]:
arrX =[]
arrY = []
arrZ = []

for i in df.columns:
  if df[i].dtype == 'int64':
    arrX.append(i)
  else:
    arrY.append(i)

In [ ]:
def clean_currency(x):
    if isinstance(x, str):
        return(x.replace('$', '').replace(',', ''))
    return(x)

<class 'float'>    460
Name: Population, dtype: int64

In [ ]:
for k in arrX:
    df[k] = df[k].astype('Int64')

for j in arrY:
    df[j] = df[j].astype('category')
df['Population'].apply(type).value_counts()
def clean_currency(x):
    if isinstance(x, str):
        return(x.replace('$', '').replace(',', ''))
    return(x)
df['Population'] = df['Population'].apply(clean_currency).astype('float')
#df['Population']
df.dtypes

City                                    category
Population                               float64
Violent crime                           category
Murder and nonnegligent manslaughter       Int64
Rape (revised definition)               category
Rape (legacy definition)                category
Robbery                                 category
Aggravated assault                      category
Property crime                          category
Burglary                                category
Larceny-theft                           category
Motor vehicle theft                     category
Arson                                   category
dtype: object

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

Ответ - количественные поля: population, arson, violent crime и т.д.
Категориальные: City

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [ ]:
#колонка 1
df[df['Murder and nonnegligent manslaughter'] >= 66]

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
233,Los Angeles,"3,962,726","25,156",282,"2,209",NaN,"8,952","13,713","93,503","16,160","61,191","16,152","1,131"
281,Oakland,"419,481","6,051",85,285,NaN,"3,290","2,391","24,568","3,333","14,846","6,389",179

In [ ]:
#колонка 2
df[df['Population'] > 1234567]

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
233,Los Angeles,3962726.0,"25,156",282,"2,209",NaN,"8,952","13,713","93,503","16,160","61,191","16,152","1,131"
351,San Diego,1400467.0,"5,582",37,566,NaN,"1,378","3,601","29,158","5,129","18,933","5,096",174

In [ ]:
#колонка 3
df[(df['Murder and nonnegligent manslaughter'] < 2)  & (df['Population'] > 111111)]

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
36,Berkeley,120387.0,530,1,44,NaN,330,155,"5,906","1,090","4,099",717,22
61,Carlsbad,113972.0,172,0,33,NaN,38,101,"2,134",366,"1,627",141,8
93,Costa Mesa3,113477.0,386,1,53,NaN,122,210,"4,723",698,"3,558",467,18
123,Elk Grove,166183.0,586,1,33,NaN,105,447,"3,120",589,"2,294",237,4
149,Fullerton3,140771.0,389,0,66,NaN,110,213,"3,893",468,"2,958",467,15
180,Huntington Beach,203233.0,420,0,52,NaN,117,251,"4,942",723,"3,846",373,23
343,Roseville,131039.0,239,0,23,NaN,84,132,"3,295",521,"2,469",305,10
370,Santa Clara,123562.0,156,1,20,NaN,71,64,"3,579",583,"2,598",398,10
389,Simi Valley3,127472.0,174,1,24,NaN,45,104,"1,513",255,"1,146",112,6
405,Sunnyvale,152443.0,158,1,29,NaN,61,67,"2,355",545,"1,514",296,9
410,Temecula,111673.0,114,1,8,NaN,47,58,"2,917",459,"2,116",342,3
412,Thousand Oaks,129976.0,136,0,26,NaN,23,87,"1,577",234,"1,241",102,9

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [ ]:
#Группировка
df.groupby('Population').mean()

<ipython-input-165-94c5e9f5edf3>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Population').mean()

            Murder and nonnegligent manslaughter
Population
115.0                                        1.0
206.0                                        0.0
339.0                                        2.0
680.0                                        0.0
705.0                                        0.0
...                                          ...
520837.0                                    39.0
863782.0                                    53.0
1031458.0                                   30.0
1400467.0                                   37.0
3962726.0                                  282.0

[460 rows x 1 columns]

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация